import React, { useEffect } from 'react';
import Head from 'next/head';

import AOS from 'aos';
import 'aos/dist/aos.css';

import Header from './components/Header';
import Sectionabouthero from './components/about/Sectionabouthero';
import Aboutcontent from './components/about/Aboutcontent';
import Sectioncontact from './components/index/Sectioncontact';
import Footer from './components/Footer';

export default function About() {

    useEffect(() => {
        AOS.init();
    }, []);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon1.ico" />
            </Head>

            <main>
                <Header />

                <Sectionabouthero />

                <Aboutcontent />
                <Sectioncontact />
            </main>

            <Footer />

        </div>
    )
}