import React, { useEffect } from "react";
import Head from 'next/head';
import AOS from 'aos';
import 'aos/dist/aos.css';

import Header from "./components/Header";
import Footer from "./components/Footer";
import Sectioncareerhero from "./components/careers/Sectioncareerhero";
import Careercontent from "./components/careers/Careercontent";
import Sectioncontact from "./components/index/Sectioncontact";

export default function Careers() {
    useEffect(() => {
        AOS.init();
    }, []);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon1.ico" />
            </Head>

            <Header />
            <main>
                <Sectioncareerhero />
                <Careercontent />
            </main>
            <Footer />
        </div>
    )
}