import React, { useEffect } from "react";
import Head from 'next/head';
import AOS from 'aos';
import 'aos/dist/aos.css';

import Header from './components/Header';
import Footer from "./components/Footer";
import Sectioncontact from "./components/index/Sectioncontact";

import Icon1 from '../public/images/illustrations/icon_contact_1.svg';
import Icon2 from '../public/images/illustrations/icon_contact_2.svg';
import Bridge from '../public/images/illustrations/bridge.svg';
import Uptodate from '../public/images/illustrations/stayupdate.svg';

export default function Contact() {
    useEffect(() => {
        AOS.init();
    }, []);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon1.ico" />
            </Head>

            <Header />
            <div className="hero"></div>
            <Sectioncontact />

            <section className="section-location">
                <div className="container">
                    <div className="row">
                        <div className="col-md-5">
                            <div className="float">
                                <h1 className="title">
                                    A Remote Company <br />
                                    HQ'd out of Dumbo, <br />
                                    Brooklyn
                                </h1>

                                <div className="d-flex">
                                    <img src={Icon1.src} alt="phone" />
                                    <p>(347) 619-3312</p>
                                </div>

                                <div className="d-flex">
                                    <img src={Icon2.src} alt="email" />
                                    <p>start@lilosocial.com</p>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-7 mt-2">
                            <img src={Bridge.src} alt="bridge" />
                        </div>
                    </div>
                </div>
            </section>

            <section className="section-uptodate">
                <div className="container">
                    <div className="row align-items-center">
                        <div className="col-md-6">
                            <h1 className="title">Stay up to date</h1>
                            <p>Subscribe to our mailing list to get the latest news and case studies directly in your inbox.</p>

                            <form action="#" id="newsletter-form">
                                <div className="form-group">
                                    <label htmlFor="email">Email Address<span>*</span> </label>
                                    <input type="email" name="email" id="email" />
                                </div>
                                <p className="hidden">Thank you for subscribing</p>
                                <input type="submit" value="Subscribe" className="btn btn-outline reverse mt-4" />
                            </form>
                        </div>
                        <div className="col-md-6">
                            <img src={Uptodate.src} alt="stay" />
                        </div>
                    </div>
                </div>
            </section>
            <Footer />
        </div>
    )
} 