import React, { useEffect } from 'react';
import Head from 'next/head';
import AOS from 'aos';
import 'aos/dist/aos.css';

import Header from './components/Header';
import Footer from './components/Footer';
import Sectioncontact from './components/index/Sectioncontact';
import Creativehero from './components/creative/Creativehero';
import Creativecontent from './components/creative/Creativecontent';

export default function creative() {
    useEffect(() => {
        AOS.init();
    }, [])

    return (
        <div>
            <Head>
                <title>Lilo Social || Landing Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon1.ico" />
            </Head>

            <Header />
            <main>
                <Creativehero />
                <Creativecontent />
                <Sectioncontact />
            </main>
            <Footer />
        </div>
    )
}
