import React, { useEffect } from 'react';
import Head from 'next/head';
// import Script from 'next/script';
// import dynamic from 'next/dynamic';

import AOS from 'aos';
import 'aos/dist/aos.css';

import Header from './components/Header';
import Sectionhero from './components/index/Sectionhero';
import Sectionclients from './components/index/Sectionclients';
import Sectionabout from './components/index/Sectionabout';
import Sectionservices from './components/index/Sectionservices';
import Sectionpartners from './components/index/Sectionpartners';
import Sectionteam from './components/index/Sectionteam';
import Sectionblockquote from './components/index/Sectionblockquote';
import Sectionsupport from './components/index/Sectionsupport';
import Sectioncontact from './components/index/Sectioncontact';
import Footer from './components/Footer';

import NY from '../public/images/clients/NY.svg';
import User from '../public/images/sarah-bishop.png';

export default function Home() {

  useEffect(() => {
    AOS.init();
  }, [])

  return (
    <div>
      
      <Head>
        <title>Lilo Social || Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon1.ico" />
      </Head>

      <main>
       <Header />
        {/* <h1>Lilo Next JS</h1> */}
        
          <Sectionhero />

          <Sectionclients />

          <Sectionabout />

          <Sectionservices />

          <Sectionpartners />

          <Sectionteam />

          <Sectionblockquote
            title="We can expect the same high standard and excellent quality of work from anyone on the team."
            subtitle="We truly rely on them to be our voice to our fan base. They’ve become a fantastic extension of our internal team and a
          trusted partner in our daily work, which alleviates a lot of stress for our internal team."
            profileimg={User.src}
            name="Sarah Bishop"
            position="VP of Marketing, NYC FC"
            company={NY.src} />

          <Sectionsupport />

          <Sectioncontact />
      </main>

      <Footer />
    </div>
  )
}
